services:
  app:
    image: raedbari/docker-demo-site:1.0
    ports:
      - "8089:8080"
    environment:
      PORT: 8080
      DB_HOST: db
      DB_PORT: 3306
      DB_NAME: myapp
      DB_USER: appuser
      DB_PASSWORD: apppass
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped

#   db:
#     image: mysql:8
#     environment:
#       MYSQL_ROOT_PASSWORD: rootpass
#       MYSQL_DATABASE: myapp
#       MYSQL_USER: appuser
#       MYSQL_PASSWORD: apppass
#     volumes:
#       - db-data:/var/lib/mysql
#     healthcheck:
#       test: ["CMD-SHELL", "mysqladmin ping -h localhost -prootpass || exit 1"]
#       interval: 5s
#       timeout: 3s
#       retries: 20
#     restart: unless-stopped

# volumes:
#   db-data: